added remote function

diff --git a/gitpushy-common b/gitpushy-common
--- a/gitpushy-common
+++ b/gitpushy-common
@@ -210,10 +210,11 @@ gitpushy-push-branch() {
 	# export pushy variables to main environment
 	export PUSHY_DEPLOY_DIR=""
 	export PUSHY_BUILD_DIR="$PWD/pushy-$1-build/"
-	export PUSHY_STAGE_DIR="$HOME/pushy-staging-$PUSHY_REPO-$PUSHY_BRANCH/"
+	export PUSHY_STAGE_DIR="$HOME/pushy-staging-$PUSHY_REPO-$1/"
 	export PUSHY_VERBOSE=0
 	export PUSHY_STATUS=0
 	export PUSHY_REMOTE=0
+	export PUSHY_BRANCH="$1"
 	export PUSHY_SERVER=$(hostname)
 	export PUSHY_HOOKS=()
 	export PUSHY_HOOK=""
@@ -246,6 +247,42 @@ gitpushy-push-branch() {
 	export GIT_DIR=$REPO_DIR
 }
 
+gitpushy-push-replicate() {
+    [ -z "$1" ] && return 402
+    gitpushy-server-commit && return 401
+
+    local SERVER=""
+
+    for SERVER in $@; do
+        if gitpushy-server-is-local $SERVER; then
+            continue
+        elif git status 2>&1 1>/dev/null; then
+            echo "Pushing commit to remote $1"
+
+            git remote add $1 ssh://$PUSHY_USER@$1:$PUSHY_PORT/$PUSHY_REPO
+            git checkout -b $1
+            git fetch $1
+
+            if git merge --no-commit $1/$PUSHY_BRANCH; then
+                git commit --allow-empty -am "GitPushy Server merged $1 on $PUSHY_SERVER"
+                git push $1 $PUSHY_BRANCH
+
+                if [ $? = 0 ]; then
+                    echo "Successfully pushed to remote $1"
+                else
+                    echo "Failed to push to remote $1 with status $?"
+                fi
+            else
+                git merge --abort
+
+                echo "Cannot resolve merge conficts with remote $1 $PUSHY_BRANCH"
+            fi
+
+            git checkout $PUSHY_BRANCH
+        fi
+    done
+}
+
 gitpushy-show() {
 	# cat files in repo
 	grep -v "^\s*$" <(for file in $@; do
@@ -256,7 +293,7 @@ gitpushy-show() {
 gitpushy-init() {
 	PUSHY_REPO="$1"
 	PUSHY_BRANCHES=()
-	
+
 	[ -z "$PUSHY_REPO" ] && if [ $(git rev-parse --is-bare-repository) = true ]; then
 		PUSHY_REPO=$(basename "$PWD")
 		PUSHY_REPO=${PUSHY_REPO%.git}
@@ -284,4 +321,38 @@ gitpushy-init() {
 			gitpushy-push-branch $PUSHY_BRANCH
 		fi
 	done
+}
+
+gitpushy-server-commit() {
+    if [ -n "$(git log -1 --oneline|cut -d' ' -f2,3|grep "GitPushy Server")" ]; then
+        return 0
+    else
+        return 1
+    fi
+}
+
+gitpushy-server-ip() {
+    ping -c 1 $1 | grep -Po -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}';
+}
+
+gitpushy-local-ips() {
+    ifconfig | grep -Po '(?<=addr:)[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
+}
+
+gitpushy-in-array() {
+    local e
+
+    for e in "${@:2}"; do
+        [[ "$e" == "$1" ]] && return 0
+    done
+
+    return 1
+}
+
+gitpushy-server-is-local() {
+    if gitpushy-in-array "$(gitpushy-server-ip $1)" $(gitpushy-local-ips); then
+        return 0
+    fi
+
+    return 1
 }
