error reporting

diff --git a/gitpushy-common b/gitpushy-common
--- a/gitpushy-common
+++ b/gitpushy-common
@@ -438,9 +438,9 @@ gitpushy-push-branch() {
 
     # switch to bare repo
     [ -n "$OLD_PWD_DIR" ] && cd $OLD_PWD_DIR
+    [ $? != 0 ] && echo "GitPushy - Failed to find $OLD_PWD_DIR" >&2 && return $?
 
     # report errors
-    [ $? != 0 ] && echo "GitPushy - Failed to find $OLD_PWD_DIR" >&2 && return $?
     [ $PUSHY_STATUS != 0 ] && echo "GitPushy - Unsuccessful push branch $PUSHY_BRANCH - status $PUSHY_STATUS" >&2
 
     # reset git orientation
@@ -532,7 +532,7 @@ gitpushy-push-replicate() {
 
     # push to remote server
     if [ $REPLICA_STATUS = 0 ] && [ "$(gitpushy-committer)" = "GitPushy" ]; then
-        git push "$REPLICA_REMOTE" "$REPLICA_BRANCH:$PUSHY_BRANCH" | sed "s/^remote/$REPLICA_SERVER/g"
+        git push "$REPLICA_REMOTE" "$REPLICA_BRANCH:$PUSHY_BRANCH" 2>&1 | grep "^remote" | sed -e "s/^remote/$REPLICA_SERVER/g"
         REPLICA_STATUS=${PIPESTATUS[0]}
 
         [ $REPLICA_STATUS != 0 ] && echo "GitPushy - Failed to push $(git config --get "remote.$REPLICA_REMOTE.url")"
