New deployment structure with hotswap

diff --git a/gitpushy-common b/gitpushy-common
--- a/gitpushy-common
+++ b/gitpushy-common
@@ -245,23 +245,54 @@ gitpushy-deploy() {
 
     echo "GitPushy - Deploying $PUSHY_REPO:$PUSHY_BRANCH to $PUSHY_SERVER:$PUSHY_DEPLOY_DIR"
 
-    #prepare pushy deploy script
-    echo "$PUSHY_ENV" > $IO_CMD
-    echo "PUSHY_TRIGGER='$1'" >> $IO_CMD
-    echo "PUSHY_STATUS='$PUSHY_STATUS'" >> $IO_CMD
+    # prepare gitpushy-setup
+    echo 'gitpushy-setup() {' >> $IO_CMD
     echo 'cd "$PUSHY_DEPLOY_DIR"' >> $IO_CMD
     echo 'if [ $? != 0 ]; then' >> $IO_CMD
     echo 'echo "Deploying to blank directory: $PUSHY_DEPLOY_DIR"' >> $IO_CMD
+    echo 'elif [ -n "$PUSHY_DEPLOY_HOTSWAP" ]; then' >> $IO_CMD
+    echo 'OLD_HOTSWAP=$(readlink $PUSHY_DEPLOY_DIR)' >> $IO_CMD
     echo 'elif [ -n "$PUSHY_DEPLOY_ARCHIVE" ]; then' >> $IO_CMD
     echo 'tar czf "$PUSHY_DEPLOY_ARCHIVE.tgz" .' >> $IO_CMD
     echo 'fi' >> $IO_CMD
-    echo 'rm -rf $PUSHY_DEPLOY_DIR' >> $IO_CMD
     echo 'cd "$PUSHY_STAGE_DIR"' >> $IO_CMD
     echo '[ $? != 0 ] && echo "No stage directory: $PUSHY_STAGE_DIR" >&2 && exit 404' >> $IO_CMD
-    echo 'rsync -a --exclude='gitpushy-*' "$PUSHY_STAGE_DIR/" "$PUSHY_DEPLOY_DIR/" --delete' >> $IO_CMD
+    echo 'rsync -a --exclude='gitpushy-*' "$PUSHY_STAGE_DIR/" "$PUSHY_DEPLOY_DIR$PUSHY_DEPLOY_HOTSWAP/" --delete' >> $IO_CMD
+    echo 'if [ -n "$PUSHY_DEPLOY_HOTSWAP" ]; then' >> $IO_CMD
+    echo 'ln -sfn "$PUSHY_DEPLOY_DIR$PUSHY_DEPLOY_HOTSWAP" "$PUSHY_DEPLOY_DIR"' >> $IO_CMD
+    echo 'fi' >> $IO_CMD
+    echo '}' >> $IO_CMD
+
+    # prepare gitpushy-transact
+    echo 'gitpushy-transact() {' >> $IO_CMD
     echo 'cd "$PUSHY_DEPLOY_DIR"' >> $IO_CMD
-    echo '[ $? != 0 ] && echo "Deployment failed to $PUSHY_DEPLOY_DIR" >&2 && exit 404' >> $IO_CMD
+    echo '[ $? != 0 ] && echo "Deployment failed to $PUSHY_DEPLOY_DIR" >&2 && PUSHY_STATUS=404' >> $IO_CMD
     gitpushy-script deploy $1 >> $IO_CMD
+    echo '}' >> $IO_CMD
+
+    # prepare gitpushy-rollback
+    echo 'gitpushy-rollback() {' >> $IO_CMD
+    echo 'if [ -n "$OLD_HOTSWAP" ]; then' >> $IO_CMD
+    echo 'echo "Rolling back to previous hot swap $OLD_HOTSWAP"' >> $IO_CMD
+    echo 'ln -sfn "$OLD_HOTSWAP" "$PUSHY_DEPLOY_DIR"' >> $IO_CMD
+    echo 'gitpushy-transact' >> $IO_CMD
+    echo 'elif [ -f "$PUSHY_DEPLOY_ARCHIVE.tgz" ]; then' >> $IO_CMD
+    echo 'echo "Rolling back to previous $PUSHY_DEPLOY_ARCHIVE"' >> $IO_CMD
+    echo 'rm "$PUSHY_DEPLOY_DIR" > /dev/null' >> $IO_CMD
+    echo 'mkdir "$PUSHY_DEPLOY_DIR"' >> $IO_CMD
+    echo 'cd "$PUSHY_DEPLOY_DIR"' >> $IO_CMD
+    echo 'tar xzf "$PUSHY_DEPLOY_ARCHIVE.tgz" .' >> $IO_CMD
+    echo 'gitpushy-transact' >> $IO_CMD
+    echo 'fi' >> $IO_CMD
+    echo '}' >> $IO_CMD
+
+    #prepare running
+    echo "$PUSHY_ENV" > $IO_CMD
+    echo "PUSHY_TRIGGER='$1'" >> $IO_CMD
+    echo "PUSHY_STATUS='$PUSHY_STATUS'" >> $IO_CMD
+    echo '[ $PUSHY_STATUS = 0 ] && gitpushy-setup' >> $IO_CMD
+    echo '[ $PUSHY_STATUS = 0 ] && gitpushy-transact' >> $IO_CMD
+    echo '[ $PUSHY_STATUS != 0 ] && gitpushy_rollback' >> $IO_CMD
     echo 'exit $PUSHY_STATUS' >> $IO_CMD
 
     # show commands run if verbosity is set
