test update

diff --git a/gitpushy-common b/gitpushy-common
--- a/gitpushy-common
+++ b/gitpushy-common
@@ -257,6 +257,7 @@ gitpushy-push-replicate() {
         if gitpushy-server-is-local $SERVER; then
             continue
         elif git status 2>/dev/null 1>/dev/null; then
+                echo "GitPushy - Syncronizing with ssh://$PUSHY_USER@$1:$PUSHY_PORT/$PUSHY_REPO"
             git remote add $1 ssh://$PUSHY_USER@$1:$PUSHY_PORT/$PUSHY_REPO
             git checkout -b $1 1>/dev/null 2>/dev/null
             git fetch $1 1>/dev/null 2>/dev/null
@@ -268,9 +269,9 @@ gitpushy-push-replicate() {
                 git push $1 $1:$PUSHY_BRANCH 1>/dev/null 2>/dev/null
 
                 if [ $? = 0 ]; then
-                    echo "GitPushy - Successfully syncronized ssh://$PUSHY_USER@$1:$PUSHY_PORT/$PUSHY_REPO"
+                    echo "GitPushy - Successfully syncronized!"
                 else
-                    echo "GitPushy - Failed syncronize with ssh://$PUSHY_USER@$1:$PUSHY_PORT/$PUSHY_REPO"
+                    echo "GitPushy - Failed syncronize to $1 with status $?"
                 fi
             else
                 git merge --abort >/dev/null
