fixed branch hooks bug

diff --git a/gitpushy-common b/gitpushy-common
--- a/gitpushy-common
+++ b/gitpushy-common
@@ -16,7 +16,7 @@ gitpushy-branch-name() {
 
 gitpushy-build() {
 	# check pushy status
-	[ $PUSHY_STATUS != 0 ] && return $PUSHY_STATUS 
+	[ $PUSHY_STATUS != 0 ] && return $PUSHY_STATUS
 
 	echo "GitPushy - Building $PUSHY_REPO:$PUSHY_BRANCH for deployment on $PUSHY_SERVER"
 
@@ -35,7 +35,9 @@ gitpushy-build() {
 	echo "PUSHY_DEPLOYMENT='$1'" >> gitpushy-$PUSHY_DEPLOYMENT-build.command
 	echo "PUSHY_STATUS='$PUSHY_STATUS'" >> gitpushy-$PUSHY_DEPLOYMENT-build.command
 	echo "cd $PUSHY_BUILD_DIR" >> gitpushy-$PUSHY_DEPLOYMENT-build.command
+
 	gitpushy-show .gitpushy-build .gitpushy-$1-build >> gitpushy-$PUSHY_DEPLOYMENT-build.command
+
 	echo "$PUSHY_SYNC" >> gitpushy-$PUSHY_DEPLOYMENT-build.command
 	echo "exit $PUSHY_STATUS" >> gitpushy-$PUSHY_DEPLOYMENT-build.command
 
@@ -44,8 +46,10 @@ gitpushy-build() {
 
 	# run pushy build srcipts
 	(cat gitpushy-$PUSHY_DEPLOYMENT-build.command | bash) 1> >(tee gitpushy-$PUSHY_DEPLOYMENT-build.output) 2> >(tee gitpushy-$PUSHY_DEPLOYMENT-build.error) | tr '\n' '\0' | xargs -0 -I {} echo "GitPushy - .gitpushy-$1-build - {}"
+
 	# capture execution status
 	PUSHY_STATUS=${PIPESTATUS[0]}
+
 	[ -s gitpushy-$PUSHY_DEPLOYMENT-build.error ] && PUSHY_STATUS=500
 
 	# return pushy status
@@ -120,7 +124,7 @@ gitpushy-deploy() {
 
 gitpushy-trigger() {
 	# check pushy status
-	[ $PUSHY_STATUS != 0 ] && return $PUSHY_STATUS 
+	[ $PUSHY_STATUS != 0 ] && return $PUSHY_STATUS
 
 	# prepare pushy config script
 	PUSHY_CONFIG="$(gitpushy-show .gitpushy-config .gitpushy-$1-config)"
@@ -136,10 +140,10 @@ gitpushy-trigger() {
 	# capture exit status
 	PUSHY_STATUS=$?
 	[ -s gitpushy-$PUSHY_DEPLOYMENT-config.error ] && PUSHY_STATUS=500
-		
+
 	# set pushy remote vs local
 	[ "$PUSHY_SERVER" != "$(hostname)" ] && PUSHY_REMOTE=1
-	
+
 	# setup pushy environment variables
 	export PUSHY_ENV="
 	PUSHY_DEPLOY_DIR='$PUSHY_DEPLOY_DIR/'
@@ -174,7 +178,7 @@ gitpushy-trigger() {
 
 		# run custom script
 		(eval "$PUSHY_CUSTOM" 1> >(tee gitpushy-$PUSHY_DEPLOYMENT-custom.output) 2> >(tee gitpushy-$PUSHY_DEPLOYMENT-custom.error))
-		
+
 		# capture exit status
 		PUSHY_STATUS=$?
 		[ -s gitpushy-$PUSHY_DEPLOYMENT-custom.errlog ] && PUSHY_STATUS=500
@@ -190,6 +194,7 @@ gitpushy-trigger() {
 		gitpushy-deploy $PUSHY_DEPLOYMENT
 	else
 		local DEPLOYMENT_RUN="$PUSHY_DEPLOYMENT config"
+
 		echo "GitPushy - Invalid config no deploy directory"
 
 		PUSHY_STATUS=500
@@ -215,21 +220,39 @@ gitpushy-push-branch() {
 	export PUSHY_STATUS=0
 	export PUSHY_REMOTE=0
 	export PUSHY_BRANCH="$1"
-	export PUSHY_SERVER=$(hostname)
+	export PUSHY_SERVER="$HOSTNAME"
 	export PUSHY_TRIGGERS=()
 	export PUSHY_DEPLOYMENT=""
 	export PUSHY_PORT=22
 	export PUSHY_USER=$(whoami)
 	export PUSHY_REPO="$PUSHY_REPO"
 
+    # Process GitPushy Brnach Hooks
+	if [ -f $GIT_DIR/hooks/pushy-$PUSHY_BRANCH-branch ]; then
+		echo "GitPushy - Custom GitPushy Hook: pushy-$PUSHY_BRANCH-branch"
+		source $GIT_DIR/hooks/pushy-$PUSHY_BRANCH-branch
+
+		return $PUSHY_STATUS
+	fi
+
+	# check if branch exists
+	[ -z "$PUSHY_BRANCH" ] && "BRANCH was not passed to gitpushy-push-branch" && return 1
+	[ ! -f $GIT_DIR/refs/heads/$PUSHY_BRANCH ] && echo "$PUSHY_BRANCH does not exist in $PUSHY_REPO" && return 1
+
 	# check if this branch has gitpushy data
-	[ -z "$(gitpushy-show .gitpushy-config .gitpushy-main .gitpushy-main-custom)" ] && return 0
+	[ -z "$(gitpushy-show .gitpushy-config .gitpushy-main-config .gitpushy-main-custom)" ] && return 0
+
+	# make a clean local clone
+	(rm -rf $PUSHY_BUILD_DIR; git clone -b $PUSHY_BRANCH . $PUSHY_BUILD_DIR) >/dev/null
+
+	# switch to clone
+	cd $PUSHY_BUILD_DIR
 
 	# reorient git
 	local REPO_DIR=$GIT_DIR
 	export GIT_DIR=$PUSHY_BUILD_DIR/.git
 
-	# run main deployment
+	# run main trigger
 	gitpushy-trigger main
 
 	# loop through addtional triggers
@@ -242,43 +265,46 @@ gitpushy-push-branch() {
 }
 
 gitpushy-push-replicate() {
-    [ -z "$1" ] && return 402
-    [ "$(gitpushy-committer)" = "GitPushy" ] && return 401
+	[ -z "$1" ] && return 402
+	[ "$(gitpushy-committer)" = "GitPushy" ] && return 401
 
-    local SERVER=""
+	local SERVER=""
 
-    for SERVER in $@; do
-        if gitpushy-server-is-local $SERVER; then
-            continue
-        elif git status 1>/dev/null 2>/dev/null; then
-                echo "GitPushy - Syncronizing $1"
-            git remote add $1 ssh://$PUSHY_USER@$1:$PUSHY_PORT/$PUSHY_REPO
-            git checkout -b $1 1>/dev/null 2>/dev/null
-            git fetch $1 1>/dev/null 2>/dev/null
+	for SERVER in $@; do
+		if gitpushy-server-is-local $SERVER; then
+			continue
+		elif git status 1>/dev/null 2>/dev/null; then
+			echo "GitPushy - Syncronizing $1"
 
-            if [ $? != 0 ]; then
-                echo "GitPushy - Failed to fetch ssh://$PUSHY_USER@$1:$PUSHY_PORT/$PUSHY_REPO"
-            elif git merge --no-commit $1/$PUSHY_BRANCH $1 1>/dev/null 2>/dev/null; then
-                git commit --author="GitPushy <$PUSHY_USER@$PUSHY_SERVER>" --allow-empty -am "Auto-merged from $1 on $PUSHY_SERVER" 1>/dev/null 2>/dev/null
-                git push $1 $1:$PUSHY_BRANCH 1>/dev/null 2>/dev/null
+			git remote add $1 ssh://$PUSHY_USER@$1:$PUSHY_PORT/$PUSHY_REPO
+			git checkout -b $1 1>/dev/null 2>/dev/null
+			git fetch $1 1>/dev/null 2>/dev/null
 
-                if [ $? = 0 ]; then
-                    echo "GitPushy - Syncronization complete!"
-                else
-                    echo "GitPushy - Failed syncronize to $1 with status $?"
-                fi
-            else
-                git merge --abort 1>/dev/null 2>/dev/null
+			if [ $? != 0 ]; then
+				echo "GitPushy - Failed to fetch ssh://$PUSHY_USER@$1:$PUSHY_PORT/$PUSHY_REPO"
+			elif git merge --no-commit $1/$PUSHY_BRANCH $1 1>/dev/null 2>/dev/null; then
+				git commit --author="GitPushy <$PUSHY_USER@$PUSHY_SERVER>" --allow-empty -am "Auto-merged from $1 on $PUSHY_SERVER" 1>/dev/null 2>/dev/null
+				git push $1 $1:$PUSHY_BRANCH 1>/dev/null 2>/dev/null
 
-                echo "Cannot resolve merge conficts with remote $1 $PUSHY_BRANCH"
-            fi
+				if [ $? = 0 ]; then
+					echo "GitPushy - Syncronization complete!"
+				else
+					echo "GitPushy - Failed syncronize to $1 with status $?"
+				fi
+			else
+				git merge --abort 1>/dev/null 2>/dev/null
 
-            git checkout $PUSHY_BRANCH 1>/dev/null 2>/dev/null
-        fi
-    done
+				echo "Cannot resolve merge conficts with remote $1 $PUSHY_BRANCH"
+			fi
+
+			git checkout $PUSHY_BRANCH 1>/dev/null 2>/dev/null
+		fi
+	done
 }
 
 gitpushy-show() {
+	[ -z "$PUSHY_BRANCH" ] && PUSHY_BRANCH=$(gitpushy-branch-name)
+
 	# cat files in repo
 	grep -v "^\s*$" <(for file in $@; do
 		git show heads/$PUSHY_BRANCH:$file 2>/dev/null
@@ -286,8 +312,9 @@ gitpushy-show() {
 }
 
 gitpushy-init() {
-	PUSHY_REPO="$1"
-	PUSHY_BRANCHES=()
+	export PUSHY_REPO=""
+	export PUSHY_BRANCH=""
+	export PUSHY_BRANCHES=()
 
 	[ -z "$PUSHY_REPO" ] && if [ $(git rev-parse --is-bare-repository) = true ]; then
 		PUSHY_REPO=$(basename "$PWD")
@@ -295,7 +322,7 @@ gitpushy-init() {
 	else
 		PUSHY_REPO=$(basename $(readlink -nf "$PWD"/..))
 	fi
-	
+
 	while read oldrev newrev refname; do
 		PUSHY_BRANCHES+=($(git rev-parse --symbolic --abbrev-ref $refname))
 	done
@@ -304,52 +331,38 @@ gitpushy-init() {
 	IFS=$'\n'
 	PUSHY_BRANCHES=($(sort -u <<<"${PUSHY_BRANCHES[@]}"))
 	IFS=$OFS;
-	
+
 	for PUSHY_BRANCH in ${PUSHY_BRANCHES[@]}; do
-	    # make a clean local clone
-	    (rm -rf $PUSHY_BUILD_DIR; git clone -b $PUSHY_BRANCH . $PUSHY_BUILD_DIR) >/dev/null
-
-	    # switch to clone
-	    cd $PUSHY_BUILD_DIR
-
-		if [ -f hooks/pushy-$PUSHY_BRANCH-branch ]; then
-			echo "GitPushy - Custom GitPushy Hook: pushy-$PUSHY_BRANCH-branch"
-			source hooks/pushy-$PUSHY_BRANCH-branch
-		elif [ $PUSHY_BRANCH != "any" ]; then
-			[ -z "$PUSHY_BRANCH" ] && echo "BRANCH was not passed to pushy-deploy" && exit 1
-			[ ! -f refs/heads/$PUSHY_BRANCH ] && exit 1
-
-			gitpushy-push-branch $PUSHY_BRANCH
-		fi
+		gitpushy-push-branch $PUSHY_BRANCH
 	done
 }
 
 gitpushy-committer() {
-    git log -1|grep -Po "(?<=Author:\s).*(?=\s+\<)"
+	git log -1|grep -Po "(?<=Author:\s).*(?=\s+\<)"
 }
 
 gitpushy-server-ip() {
-    ping -c 1 $1 | grep -Po -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}';
+	ping -c 1 $1 | grep -Po -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}';
 }
 
 gitpushy-local-ips() {
-    ifconfig | grep -Po '(?<=addr:)[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
+	ifconfig | grep -Po '(?<=addr:)[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
 }
 
 gitpushy-in-array() {
-    local x
+	local x
 
-    for x in "${@:2}"; do
-        [ "$x" = "$1" ] && return 0
-    done
+	for x in "${@:2}"; do
+		[ "$x" = "$1" ] && return 0
+	done
 
-    return 1
+	return 1
 }
 
 gitpushy-server-is-local() {
-    if gitpushy-in-array "$(gitpushy-server-ip $1)" $(gitpushy-local-ips); then
-        return 0
-    fi
+	if gitpushy-in-array "$(gitpushy-server-ip $1)" $(gitpushy-local-ips); then
+		return 0
+	fi
 
-    return 1
+	return 1
 }
