added better error reporting

diff --git a/gitpushy-common b/gitpushy-common
--- a/gitpushy-common
+++ b/gitpushy-common
@@ -425,8 +425,10 @@ gitpushy-push-branch() {
         done
     fi
 
-    # clean up after deploy unless we explicitly keep the dir
-    [ -z "$PUSHY_BUILD_KEEP" ] && gitpushy-clean-temp $PUSHY_BUILD_DIR
+    # clean up after deploy
+    gitpushy-clean-temp $PUSHY_BUILD_DIR
+
+    [ $? != 0 ] && echo "GitPushy - Failed to remove $PUSHY_BUILD_DIR" >&2 && return $?
 
     # reset git orientation
     export GIT_DIR=$REPO_DIR
@@ -567,11 +569,11 @@ gitpushy-clean-temp() {
     local CLEAN_STATUS=0
     [ -z "$1" ] && echo "GitPushy - No build directory specified" && local CLEAN_STATUS=404
     [ $PUSHY_STATUS != 0 ] && echo "GitPushy - Leaving build directory $1" && return 500
+    [ -n "$PUSHY_BUILD_KEEP" ] && echo "GitPushy - Keeping build directory $1" && return 0
 
     if [ $CLEAN_STATUS = 0 ]; then
-        (rm -rf $1) 1>/dev/null 2>/dev/null
-
-        local CLEAN_STATUS=${PIPESTATUS[0]}
+        rm -rf $1 1>/dev/null 2>/dev/null
+        local CLEAN_STATUS=$?
 
         # switch to clone
         [ -n "$PUSHY_BARE" ] && cd $PUSHY_BARE
